"""user model

Revision ID: fb33b0f04443
Revises: 05a14c4a9980
Create Date: 2024-02-12 22:01:36.913080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb33b0f04443'
down_revision = '05a14c4a9980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.drop_index('whatsapp_number')
        batch_op.create_unique_constraint(None, ['phone_number'])
        batch_op.drop_column('whatsapp_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_number', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('whatsapp_number', ['whatsapp_number'], unique=True)
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
